-- Add new columns to School table
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "institutionCode" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "schoolType" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "schoolPhone" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "contactPhone" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "bankCode" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "bankBranch" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "bankAccount" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "notes" TEXT;
