-- Add new columns to Gafan table for the full form
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "programNumber" VARCHAR(50);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "validYear" INTEGER;
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "companyName" VARCHAR(255);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "companyId" VARCHAR(50);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "companyAddress" TEXT;
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "bankName" VARCHAR(100);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "bankCode" VARCHAR(10);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "branchNumber" VARCHAR(20);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "accountNumber" VARCHAR(30);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "operatorName" VARCHAR(255);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "priceMin" NUMERIC(10,2);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "priceMax" NUMERIC(10,2);
ALTER TABLE "Gafan" ADD COLUMN IF NOT EXISTS "notes" TEXT;

-- Make schoolId nullable since it's not required in the new form
ALTER TABLE "Gafan" ALTER COLUMN "schoolId" DROP NOT NULL;
