-- Add missing columns to Student table
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "idNumber" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "father" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "mother" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "additionalPhone" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "healthFund" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "allergies" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "totalSessions" INTEGER DEFAULT 12;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "courseIds" JSONB DEFAULT '[]';
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "courseSessions" JSONB DEFAULT '{}';
