-- Add missing fields to Teacher table
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "idNumber" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "birthDate" DATE;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "centerHourlyRate" NUMERIC;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "travelRate" NUMERIC;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "externalCourseRate" NUMERIC;
